--zad1
SELECT NAZWISKO, ETAT, P.ID_ZESP, NAZWA 
FROM PRACOWNICY P INNER JOIN ZESPOLY Z ON P.ID_ZESP = Z.ID_ZESP 
ORDER BY NAZWISKO;
--zad2
SELECT NAZWISKO, ETAT, P.ID_ZESP, NAZWA 
FROM PRACOWNICY P INNER JOIN ZESPOLY Z ON P.ID_ZESP = Z.ID_ZESP 
WHERE Z.ADRES = 'PIOTROWO 3A' 
ORDER BY NAZWISKO;
--zad3
SELECT NAZWISKO, ETAT, PLACA_POD, PLACA_MIN, PLACA_MAX 
FROM PRACOWNICY P INNER JOIN ETATY E ON ETAT = NAZWA 
ORDER BY ETAT, NAZWISKO;
--zad4
SELECT NAZWISKO, ETAT, PLACA_POD, PLACA_MIN, PLACA_MAX, 
CASE WHEN PLACA_POD < PLACA_MIN THEN 'NIE' WHEN PLACA_POD > placa_max THEN 'NIE' ELSE 'OK' END AS CZY_PENSJA_OK 
FROM PRACOWNICY P INNER JOIN ETATY E ON ETAT = NAZWA 
ORDER BY ETAT, NAZWISKO;
--zad5
SELECT NAZWISKO, ETAT, PLACA_POD, PLACA_MIN, PLACA_MAX, CASE WHEN PLACA_POD < PLACA_MIN THEN 'NIE' WHEN PLACA_POD > placa_max THEN 'NIE' ELSE 'OK' END AS CZY_PENSJA_OK 
FROM PRACOWNICY P INNER JOIN ETATY E ON ETAT = NAZWA 
WHERE PLACA_POD > PLACA_MAX OR PLACA_POD < PLACA_MIN 
ORDER BY ETAT, NAZWISKO;
--zad6
SELECT NAZWISKO, PLACA_POD, ETAT, NAZWA AS KAT_PLAC, PLACA_MIN, PLACA_MAX 
FROM PRACOWNICY P INNER JOIN ETATY E ON PLACA_POD BETWEEN PLACA_MIN AND PLACA_MAX 
ORDER BY NAZWISKO, KAT_PLAC;
--zad7
SELECT NAZWISKO, PLACA_POD, ETAT, NAZWA AS KAT_PLAC, PLACA_MIN, PLACA_MAX 
FROM PRACOWNICY P INNER JOIN ETATY E ON PLACA_POD BETWEEN PLACA_MIN AND PLACA_MAX WHERE NAZWA LIKE 'SEKRETARKA' 
ORDER BY NAZWISKO, KAT_PLAC;
--zad8
SELECT P.NAZWISKO AS PRACOWNIK, P.ID_PRAC, R.NAZWISKO AS SZEF, P.ID_SZEFA 
FROM PRACOWNICY P INNER JOIN PRACOWNICY R ON P.ID_SZEFA =   R.ID_PRAC 
ORDER BY PRACOWNIK;
--zad9
SELECT P.NAZWISKO AS PRACOWNIK, P.ZATRUDNIONY as PRAC_ZATRUDNIONY, S.NAZWISKO AS SZEF, S.ZATRUDNIONY as SZEF_ZATRUDNIONY, FLOOR((P.ZATRUDNIONY - S.ZATRUDNIONY) / 365) AS LATA 
FROM PRACOWNICY P INNER JOIN PRACOWNICY S ON P.ID_SZEFA = S.ID_PRAC 
WHERE FLOOR((P.ZATRUDNIONY - S.ZATRUDNIONY) / 365) < 10 ORDER BY FLOOR((P.ZATRUDNIONY - S.ZATRUDNIONY) / 365), P.NAZWISKO;
--zad10
SELECT NAZWA, COUNT(Z.NAZWA) AS LICZBA, AVG(P.PLACA_POD) AS SREDNIA_PLACA 
FROM PRACOWNICY P INNER JOIN ZESPOLY Z ON P.ID_ZESP = Z.ID_ZESP 
GROUP BY P.ID_ZESP, Z.NAZWA 
ORDER BY NAZWA;
--zad11
SELECT NAZWA, CASE WHEN COUNT(Z.NAZWA) <=2 THEN 'MALY' WHEN COUNT(Z.NAZWA) >=3 AND COUNT(Z.NAZWA) <=6 THEN 'SREDNI' ELSE 'DUZY' END AS ETYKIETA 
FROM PRACOWNICY P INNER JOIN ZESPOLY Z ON P.ID_ZESP = Z.ID_ZESP 
GROUP BY P.ID_ZESP, Z.NAZWA
ORDER BY NAZWA;