--zad1
SELECT NAZWISKO, Z.ID_ZESP, NAZWA 
FROM PRACOWNICY P LEFT OUTER JOIN ZESPOLY Z ON P.ID_ZESP = Z.ID_ZESP 
ORDER BY NAZWISKO;
--zad2
SELECT NAZWA, Z.ID_ZESP, COALESCE(NAZWISKO, 'brak pracowników') as PRACOWNIK 
FROM PRACOWNICY P RIGHT OUTER JOIN ZESPOLY Z ON P.ID_ZESP = Z.ID_ZESP 
ORDER BY NAZWA, NAZWISKO;
--zad3
SELECT COALESCE(NAZWA, 'brak zespolu') AS ZESPOL, COALESCE(NAZWISKO, 'brak pracowników') as PRACOWNIK 
FROM PRACOWNICY P FULL OUTER JOIN ZESPOLY Z ON P.ID_ZESP = Z.ID_ZESP 
ORDER BY NAZWA, NAZWISKO;
--zad4
SELECT Z.NAZWA AS ZESPOL, COUNT(NAZWISKO) as LICZBA, SUM(PLACA_POD) AS SUMA_PLAC 
FROM PRACOWNICY P RIGHT OUTER JOIN ZESPOLY Z ON P.ID_ZESP = Z.ID_ZESP 
GROUP BY NAZWA 
ORDER BY ZESPOL;
--zad5
SELECT Z.NAZWA 
FROM PRACOWNICY P RIGHT OUTER JOIN ZESPOLY Z ON P.ID_ZESP = Z.ID_ZESP 
GROUP BY NAZWA 
HAVING COUNT(NAZWISKO)=0 
ORDER BY Z.NAZWA;
--zad6
SELECT P.NAZWISKO AS PRACOWNIK, P.ID_PRAC, S.NAZWISKO AS SZEF, S.ID_PRAC AS ID_SZEFA 
FROM PRACOWNICY P LEFT OUTER JOIN PRACOWNICY S ON P.ID_SZEFA = S.ID_PRAC ORDER BY P.NAZWISKO;
--zad7
SELECT P.NAZWISKO AS PRACOWNIK, COUNT(S.NAZWISKO) as LICZBA_PODWLADNYCH 
FROM PRACOWNICY P LEFT OUTER JOIN PRACOWNICY S ON S.ID_SZEFA = P.ID_PRAC 
GROUP BY P.NAZWISKO 
ORDER BY P.NAZWISKO;
--zad8
SELECT X.NAZWISKO, X.ETAT, X.PLACA_POD, Y.NAZWA, Z.NAZWISKO AS SZEF 
FROM PRACOWNICY X LEFT OUTER JOIN PRACOWNICY Z ON X.ID_SZEFA = Z.ID_PRAC LEFT OUTER JOIN ZESPOLY Y ON X.ID_ZESP = Y.ID_ZESP 
ORDER BY X.NAZWISKO;
--zad9
SELECT NAZWISKO, NAZWA 
FROM PRACOWNICY X CROSS JOIN ZESPOLY Y 
ORDER BY NAZWISKO, NAZWA;
--zad10
SELECT COUNT(*) 
FROM PRACOWNICY X CROSS JOIN ZESPOLY Y CROSS JOIN ETATY Z;
--zad11
SELECT DISTINCT(X.ETAT) 
FROM PRACOWNICY X CROSS JOIN PRACOWNICY Y 
WHERE EXTRACT(YEAR FROM X.ZATRUDNIONY)=1992 and EXTRACT(YEAR FROM Y.ZATRUDNIONY)=1993 
ORDER BY ETAT;
--zad12
SELECT X.ID_ZESP 
FROM ZESPOLY X LEFT OUTER JOIN PRACOWNICY Y ON X.ID_ZESP = Y.ID_ZESP 
GROUP BY X.ID_ZESP 
HAVING COUNT(Y.NAZWISKO)=0 
ORDER BY X.ID_ZESP;
--zad13
SELECT ID_ZESP, NAZWA 
FROM ZESPOLY MINUS 
	SELECT X.ID_ZESP, Y.NAZWA 
	FROM PRACOWNICY X INNER JOIN ZESPOLY Y ON X.ID_ZESP = Y.ID_ZESP;
--zad14
SELECT NAZWISKO, PLACA_POD, 'Poniżej 480 złotych' AS PROG 
FROM PRACOWNICY 
WHERE PLACA_POD < 480 
UNION (SELECT NAZWISKO, PLACA_POD, 'Powyżej 480 złotych' AS PROG FROM PRACOWNICY WHERE PLACA_POD > 480) 
UNION (SELECT NAZWISKO, PLACA_POD, 'Dokladnie 480 złotych' AS PROG FROM PRACOWNICY WHERE PLACA_POD = 480) 
ORDER BY PLACA_POD;