--zad1
CREATE TABLE PROJEKTY
(ID_PROJEKTU NUMBER(4) GENERATED ALWAYS AS IDENTITY,
  OPIS_PROJEKTU VARCHAR(20CHAR),
DATA_ROZPOCZECIA DATE DEFAULT SYSDATE,
DATA_ZAKONCZENIA DATE,
FUNDUSZ NUMBER(7,2)
);

--zad2
INSERT INTO PROJEKTY(OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ)
VALUES ('Indeksy bitmapowe', '1999-04-02', '2001-06-30', 25000);
INSERT INTO PROJEKTY(OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ)
VALUES ('Sieci kręgoslupowe', DEFAULT, NULL, 19000);

--zad3
SELECT ID_PROJEKTU, OPIS_PROJEKTU
FROM PROJEKTY;

--zad4
INSERT INTO PROJEKTY
VALUES(10, 'Indeksy drzewiaste', '2013-12-24', '2014-01-01', 1200);
--ORA-32795: nie można wstawić do kolumny tożsamości utworzonej jako GENERATED ALWAYS
INSERT INTO PROJEKTY
VALUES(DEFAULT, 'Indeksy drzewiaste', '2013-12-24', '2014-01-01', 1200);

--zad5
UPDATE PROJEKTY
SET ID_PROJEKTU = 10
WHERE PROJEKTY.OPIS_PROJEKTU = 'Indeksy drzewiaste';
--ORA-32796: nie można zaktualizować kolumny tożsamości utworzonej jako GENERATED ALWAYS

--zad6
CREATE TABLE PROJEKTY_KOPIA AS SELECT * FROM PROJEKTY; 
SELECT * FROM PROJEKTY_KOPIA;

--zad7
INSERT INTO PROJEKTY_KOPIA
VALUES(10, 'Sieci lokalne', SYSDATE, SYSDATE + interval '1' year, 24500);
SELECT * FROM PROJEKTY_KOPIA;

--zad8
DELETE FROM PROJEKTY
WHERE PROJEKTY.OPIS_PROJEKTU='Indeksy drzewiaste';
SELECT * FROM PROJEKTY;
SELECT * FROM PROJEKTY_KOPIA;
--nie

--zad9
SELECT TABLE_NAME
FROM user_tables
ORDER BY TABLE_NAME;
